### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by niahoo** [FormidableLabs/redux-little-router#123]
Hi, I have a few questions about this project, but first I want to say thank you because this library is really great, and I think you understood the problem well.

My first question is : how to integrate with react-router ? As the history location is in the state I think it should be easy. Fragments are very cool but my coworkers are used to React's router. I could use redux-router package but I think it's not as easy to use as redux-little-router

My second question is how to push a location on the history ? I did not find anything about that in the docs. Do you export an action creator ?

My use case is when you load a certain page, I use a custom middleware to listen for actions and trigger other actions with variables read from the URL. Do you think it's a bad pattern ? If yes, how to trigger side effects on URL changes ? The react-redux-router team suggest to do this in the react components, but I think it's wrong to use the view layer to do that. What do you think ?

Thanks.

**Comment by tptee** [comment]
Hi @niahoo ,

I know it's been forever since you posted this, I'm sorry for just now answering and I understand if it's not relevant anymore 😞 

For your first question, I imagine `redux-little-router` and `react-router` can't really integrate, since they both control location state. However, `react-router@v4` takes a similar approach to our React bindings, so maybe you can convince your coworkers after all 😉 

To push a location on to the history, you can use this action creator:

```js
dispatch(push('/some/thing/here')
```

There's more details in the action creator section in the readme!

**Comment by niahoo** [comment]
Hi, thank you, I can't remember what was my problem right now but I may come back to that in a few. It's good to see you are around here !

Cheers
