### ISSUE TITLE
Dynamic routes

### ISSUE THREAD

**Issue by SCLeoX** [FormidableLabs/redux-little-router#169]
Is there a way to change routes object after the store is created?

**Comment by tptee** [comment]
Not yet, although it's coming up soon. I'm hoping to release #189 soon, which allows `Fragment`s to ignore static routes entirely, making them code-splittable 😄

**Comment by faceyspacey** [comment]
@SCLeoX what's the use case for changing route objects after the store is created?

**Comment by SCLeoX** [comment]
@faceyspacey The fragments are not all loaded at beginning. At beginning, we do not want to send over information about our whole site as some of them should be only accessible by an admin.

**Comment by faceyspacey** [comment]
And this isn't solved by simply making the content empty on the URLs without proper with? This is just about preventing hackers from seeing URLs correct?

**Comment by SCLeoX** [comment]
Yes. It prevents hackers from understanding our admin panel's structure.

**Comment by tptee** [comment]
Implemented a `replaceRoutes` action creator in `v14.2.0`! You'll want to look at the [advanced docs](https://github.com/FormidableLabs/redux-little-router/blob/master/ADVANCED.md#code-splitting) for usage.

If you're just using `Fragment` and not relying on the static routes for their `result` key, you're already set, since we decoupled `Fragment` from the static routes in `v14`.
