### ISSUE TITLE
Official support for `hashHistory`

### ISSUE THREAD

**Issue by dpwrussell** [FormidableLabs/redux-little-router#42]
I initially asked
> Any plans to have a `hashHistory`?

but I just tried importing 

```js
import { hashHistory } from 'react-router'
...

    createStoreWithRouter({
      routes,
      pathname: location.pathname, // optional, the beginning URL
      // basename: '',
      history: hashHistory
    }),

...
```

That actually does seem to work! It would be good to get some documentation on managing histories and if there is a hashHistory alternative to importing it from react-router which feels (although probably isn't!) very wrong!

Split out from #35

**Comment by tptee** [comment]
You're on the right track. I'd recommend importing `hashHistory` from `history` instead of `react-router`, though.

I haven't tried `hashHistory` in this project yet and it's not a huge priority for us, since the HTML5 History API enjoys widespread support. I'd definitely welcome a PR that updates our test suite to test against both `browserHistory` and `hashHistory`!

**Comment by dpwrussell** [comment]
It's actually been a long time since I really looked at how histories work. I was under the misguided impression that without server side rendering, hashHistory was the only way to go. Now I look into it again, it seems that the HTML History API will work just fine as long as I'm smart about how I query for data that each route and/or component needs.

Thanks

**Comment by tptee** [comment]
Cool, I'll reopen this if we get a good chunk of requests for it 👍
