### ISSUE TITLE
Documentation / Demo | Redux provider

### ISSUE THREAD

**Issue by fabienjuif** [FormidableLabs/redux-little-router#74]
Hello there,

When I read the doc, I assume that `redux-little-router/RouterProvider` needs the child component to be wrapped in the `redux/Provider` : 
```
redux-little-router assumes and requires that your root component is wrapped in <Provider> from react-redux. 
```

When I read the demo, this is the other way around : 
```
export default store => Root =>
  <Provider store={store}>
    <RouterProvider store={store}>
      <Root />
    </RouterProvider>
  </Provider>;
```

So my question is : **What is the best way ?**

And if you can update either the documentation either the demo code it'll be nice :)
I can do this part in a PR if you want to.

**Comment by tptee** [comment]
It's a little vague, but all that means is that your `<Root>` component should be a child of `<Provider>`.  It doesn't have do be a _direct_ child, though, so the order doesn't matter. As long as you have `<Provider>` and `<RouterProvider>` around your root component, you're good to go, since these pass context and not props.

I'll update the docs to reflect this!

**Comment by tptee** [comment]
Updated in `master`!
